language: python
python:
  - "3.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest
  - python setup.py install
  - ktpl -h

deploy:
  provider: pypi
  user: whereismyjetpack
  password:
    secure: byH5oz2kcYGjUXDiZxasnz+H4GGxPOVA2of/iJ80UwnjyZbJk8iBQBMACVx6Wm+bnYkmjhNpuJoodqsGr4bEwDYAIhEG3S9O3HpzgAvAMpZckLXegB0ngNeu3/ctP3tYE5amQkwmsag1KiKCU3Vdy9YZJpGgs/XABkfwLvz0EVWVinN3SFfvAvXDifWd8at9trBGSHH1ghaS94UiPltjetf/Tgg+/0sulmlyOuHLt8kt54Kyi73JBcDt8xW67kgF0BsD+Ej9BswRQWYU4W0rS2d/mj2lTyYzTyXmJvRuz3dPxESMXQ1pgyD8xfk+QcOxNO7hiyNF2JeBQepicAeXZox3lOM5ULafIzRtkC3r/5vIqjG1yh/u2Zx8lDhRK4mKBkF+PaXKa8R9a4DtVz+8bcuBzIgzNgLVIGq9PpwTy8FoEypwO70Zn9l7JxoZbap7GixbGv2MY6suX7CJKqlt2wUCthIvA7QUY1Q1r0OKVHVZH1Xk9Ib6m9FAfpFtUePdc8XmiF1Y7pbGLHS5InArYJ6Ubm+QhpLmec4mYmOe3EgFM10KoWgySU7+1Jjd39Di8dEb3Z9Hp+FYv0QL0dYr4eMRGHFdh58AzRD8elyO2gkVJMAq1Xon9kR4xJXNUe2Y99qnedC8hgSMpRDC7Jscc5wBRj9ktvzfyQfc1tasW4o=" 
  on:
    tags: true